# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

defaults: &defaults
  working_directory: ~/repo

version: 2
jobs:
  build:
    <<: *defaults
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run: 
          name: Install dependencies
          command: |
            yarn install --pure-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Lint
          command: |
            yarn run lint
      - run:
          name: Release
          command: |
            yarn run build
  deploy-staging:
    <<: *defaults
    docker:
      - image: google/cloud-sdk:alpine
    steps:
      - run:
        name: Upload files
        command: |
            gsutil rsync -d -r dist gs://staging.dnd-js.appspot.com/
            gsutil acl ch -u AllUsers:R gs://staging.dnd-js.appspot.com/*.css
            gsutil acl ch -u AllUsers:R gs://staging.dnd-js.appspot.com/*.js
            gsutil acl ch -u AllUsers:R gs://staging.dnd-js.appspot.com/*.html

workflows:
  version: 2
  default:
    jobs:
      - build
      - deploy
          requires:
            - build